- name: Ensure facts has been gathered
  ansible.builtin.gather_facts:

- name: Ensuring required py modules are installed
  ansible.builtin.pip:
    name: python3-dnf

- name: Ensure that firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Enabling https rule
  ansible.posix.firewalld:
    service: '{{ item }}'
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http
    - https

- name: Setting some facts to build the repo file url
  ansible.builtin.set_fact:
    os_distro: '{{ ansible_distribution | lower }}'
    os_version: '{{ ansible_distribution_version }}'

- name: Downloading the appropiate gitlab repo file
  ansible.builtin.get_url:
    url: 'https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/config_file.repo?os={{ os_distro }}&dist={{ os_version }}&source=script'
    dest: /etc/yum.repos.d/gitlab_gitlab-ee.repo

- name: installing gitlab package
  ansible.builtin.dnf:
    name:
      - perl
      - policycoreutils
      - gitlab-ee
    update_cache: true
  environment:
    EXTERNAL_URL: '{{ gitlab_external_url }}'
    GITLAB_ROOT_PASSWORD: '{{ gitlab_root_password }}'
