- name: Assert that needed variables are defined
  ansible.builtin.assert:
    that:
      - external_url is defined
      - root_password is defined
      - external_url is not none
      - root_password is not none
